wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1669420064.289154
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 3
      - 16
      - 23
      - 37
      4: 3.7.15
      5: 0.13.5
      8:
      - 5
base_filters:
  desc: null
  value: 64
batch_size:
  desc: null
  value: 256
clamp_val:
  desc: null
  value: 2.5
downsample_gap:
  desc: null
  value: 2
drop_out:
  desc: null
  value: 0.3981942107467543
epochs:
  desc: null
  value: 80
increasefilter_gap:
  desc: null
  value: 4
kernel_size:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.00945474505541757
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: maximize
    name: Test AUC_ROC
n_block:
  desc: null
  value: 16
no_cuda:
  desc: null
  value: false
num_classes:
  desc: null
  value: 1
parameters:
  desc: null
  value:
    base_filters:
      values:
      - 64
      - 128
    batch_size:
      values:
      - 128
      - 256
      - 512
    clamp_val:
      values:
      - 2
      - 2.5
      - 3
    downsample_gap:
      value: 2
    drop_out:
      max: 0.5
      min: 0.2
    epochs:
      value: 80
    increasefilter_gap:
      value: 4
    kernel_size:
      values:
      - 3
      - 7
      - 10
    lr:
      max: 0.01
      min: 0.0001
    n_block:
      value: 16
    no_cuda:
      value: false
    num_classes:
      value: 1
    pos_weight:
      values:
      - 1
      - 1.5
      - 3.16
    test_batch_size:
      value: 512
    weight_decay:
      max: 0.001
      min: 1.0e-05
pos_weight:
  desc: null
  value: 1
program:
  desc: null
  value: trainreg.py
test_batch_size:
  desc: null
  value: 512
weight_decay:
  desc: null
  value: 0.0006996540680999835
