program: trainreg.py
method: random
metric:
  name: "Test AUC_ROC"
  goal: maximize
parameters:
  num_classes:
    value: 1
  clamp_val:
    values: [2, 2.5, 3]
  batch_size:
    values: [128, 256, 512]
  test_batch_size:
    value: 512
  epochs:
    value: 80
  # loss params
  pos_weight:
    values: [1, 1.5, 3.16]
  # optimizer params
  lr:
    min: 0.0001
    max: 0.01
  weight_decay:
    min: 0.00001
    max: 0.001
  no_cuda:
    value: false
  # architecture params
  drop_out:
    min: 0.2
    max: 0.5
  base_filters:
    values: [64, 128]
  kernel_size:
    values: [3, 7, 10]
  n_block:
    value: 8
  downsample_gap:
    value: 1
  increasefilter_gap:
    value: 2
